$('.owl-carousel').owlCarousel({
    loop:true,
    Autoplay:true,
    margin:10,
    //nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})
